### ISSUE TITLE
Support import and export from The Forge

### ISSUE THREAD

**Issue by baileywick** [cstadther/adventure-import-export#103]
I am a Forge customer (https://forge-vtt.com/) and I think the core data directory is different than a self-hosted FVTT game. That might be what causes this to break when importing/exporting to/from a Forge-hosted world.

Here is an example of a path to an asset I placed in the /adventures/import/ directory.

https://assets.forge-vtt.com/5ea8c7a5da596b7e45b1c898/adventures/import/Baileywiki%20Mansion%20LVL1%202100x1300%20100ppi%20NO%20GRID%20grass.png

**Comment by cstadther** [comment]
I'm not sure I understand.  You no longer have to put the adventure file in the import folder.  You can select it with the file input and it will upload and import for you.

Are you having trouble exporting or importing?

**Comment by baileywick** [comment]
I am a Forge (hosted) user. When I export a scene from a Forge world using
Adventure Exporter, then try to import that scene to my local instance of
Foundry, I end up having to manually change all of my file references to
point to the imported files.

I want to share my maps with the community and my Patreon, but I can't
expect them to try to figure out that manual mapping. It's also possible
I'm doing something wrong.

**Comment by cstadther** [comment]
Ah makes sense.  Just as a workaround maybe until I get a fix written, I originally envisioned content creators using their local version to create the adventures so that users on hosted versions could import easily.

**Comment by baileywick** [comment]
Ah ok. So I should build my maps locally until you've worked it out.
Incidentally, I'm sure KaKaRoTo would be thrilled if you can help export
the original PNGs in a package that doesn't hit his servers everytime
someone loads the shared map. He would probably promote the module to his
community.

**Comment by 736dave** [comment]
I am a Forge user, too.  Forge has a separate ["Assets Library" (link)](https://forums.forge-vtt.com/t/the-assets-library/574) hat the the importer doesn't seem to be able to populate.  The import presents countless errors "something went wrong with your file upload request".  My imported game has no images (obviously not usable).
