### ISSUE TITLE
import file doesn't work in macOs

### ISSUE THREAD

**Issue by narukaioh** [cstadther/adventure-import-export#121]
I am not able to open the ZIP files on the mac.

I believe it is because of the "data" folder, I cannot identify where it is on my machine

![Screen Shot 2021-02-13 at 22 32 56](https://user-images.githubusercontent.com/359991/107866054-7a656500-6e4b-11eb-9de4-bf0b5bd2f9a6.png)

**Comment by cstadther** [comment]
Don't use the drop down, click Choose File and select the file to import

**Comment by narukaioh** [comment]
when I try to select the files, all zip files are not be clickable
![Uploading WhatsApp Image 2021-02-13 at 21.17.46.jpeg…]()

**Comment by narukaioh** [comment]
this is a example of my compendium for equipments: https://github.com/narukaioh/equipments

**Comment by cstadther** [comment]
the correct extension is .fvttadv.  Where did you hear you need a zip file?

**Comment by narukaioh** [comment]
Calm down, I'm not criticizing your component, I'm trying to report a problem. I didn't see anywhere, which extension was correct.

**Comment by cstadther** [comment]
Excuse me?!  Calm down?  I was merely stating that the importer does NOT use zip files.  The file selector dialog should default to .fvttadv extension.

**Comment by cstadther** [comment]
You are reading way too much into a simple question as to why you are using a zip file, and where you heard to use one... There have been people posting to use a zip file and I just want to make sure the information they are giving is correct.

**Comment by cstadther** [comment]
So some history, the data folder is actually not accessible everywhere (like the Forge) and with everyone having the folders in a different paths it was easier to add an upload button, where it would parse the file on the fly.

**Comment by narukaioh** [comment]
Sorry, it's not my native language, I'm using the translator I didn't want to be rude
