### ISSUE TITLE
Import Path problem

### ISSUE THREAD

**Issue by JoonasVerm** [cstadther/adventure-import-export#123]
I'm hosting Foundry on a linux server and accessin it via Windows pc. I'm trying to import a world but I can't get the fvttadv file to show up in the importer. What should I put in the Import Path? Should the file be at the server or on my computer? It's 2 GB so too large for the choose file method. I've tried putting it in different folders on both the server any my PC. How do I get it to show up in the importer?

**Comment by JoonasVerm** [comment]
I got it. It had to be in the installionpath import folder. That could be a bit clearer in the guide.

**Comment by cstadther** [comment]
Ahh I see.  So to get it to show up in the you need to find the data path.  I'm not sure it creates it automatically but you do specify the path when launching foundry from node example `node resources/app/main.js --dataPath=../foundrydata`

This path is the root for the import path, so if my path to foundry is `~/foundryvtt` then in the case above the path would be `~/foundrydata` and the resolved default import path would be `~/foundrydata/adventures/import`  Hope that makes sense.

**Comment by JoonasVerm** [comment]
I think because I'm runnin the nodejs versio, my path is a bit more complicated. I have a ~/foundryvtt folder where I unpacked the original istallion zip but the data files are in ~/.local/share/FoundryVTT/Data/

**Comment by cstadther** [comment]
Yea, the could be more clear for those running the node version.  :)
