### ISSUE TITLE
Request:  Maintain existing folder structure

### ISSUE THREAD

**Issue by notrealdan** [cstadther/adventure-import-export#37]
Since Foundry only allows a depth of 3 folders, forcing that everything be placed inside a new folder further limits the folder depth to effectively 2, which is very difficult to work with, especially for those of us who already have things organized and are making heavy use of all 3 levels.  I'd like to be able to keep my existing folder structures upon exporting and importing.

Could there be an option added to maintain the existing structure, rather than always put things in a folder named after the adventure?

Thanks!

**Comment by cstadther** [comment]
The main idea for this module was for add-on content to a campaign.  My main concern with removing the initial folder is, I want adventures that I import to be separated from my created content.  

However I can see the value to have the ability to export a world without having to worry about including images and such, and maintaining all folder structures.
  
I will put warnings and options for this on both the export and import.

**Comment by cstadther** [comment]
Added export option to maintain folder structure, and not create a new folder based on adventure.
