### ISSUE TITLE
"Compendium Pack Already Exists" error

### ISSUE THREAD

**Issue by ChaseDonnally** [cstadther/adventure-import-export#39]
I'm trying to import just a macro compendium pack, and I'm getting an error saying that the compendium pack already exists in the world. It definitely does not, and I've tried renaming the exported compendium pack and re-exporting and I get the same result.

![image](https://user-images.githubusercontent.com/47797620/88503057-63c9f000-cf85-11ea-8bc3-78a9c2830e18.png)

![image](https://user-images.githubusercontent.com/47797620/88503074-7c3a0a80-cf85-11ea-8425-42ecc8da9171.png)

![image](https://user-images.githubusercontent.com/47797620/88503115-97a51580-cf85-11ea-838f-9707f6ebe0b0.png)

**Comment by cstadther** [comment]
This is a know issue with the Core Foundry, where if you switch or delete worlds and the previous world had a compendium with the same name the error shows up.  
https://gitlab.com/foundrynet/foundryvtt/-/issues/2541
It looks like it may be fixed in the current alpha version for 7.1
