### ISSUE TITLE
Importer button not doing anything

### ISSUE THREAD

**Issue by KirikTheOrc** [cstadther/adventure-import-export#40]
I exported my game and saved it in the right place but when I try to import something... nothing happens.

Foundry vtt ver. 6.5
The forge vtt hosting site

**Comment by cstadther** [comment]
can you provide the file?  I'll take a look and see whats happening

**Comment by cstadther** [comment]
Added a file upload button to fix issues where the file was not in the right place or if the file permissions were off, now works in the forge hosting environment.
