### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by altair984** [cstadther/adventure-import-export#43]
First of all I would like to thank you for your effort in creating this brilliant module. Thank you very much.

I must say that the import system is very good as it is. If anything I would try to improve the fact of being able to import adventures with several folder sections, but safeguarding this I find the adventure directory and within its import folder very good.

https://i.imgur.com/ApA3heM.png

The problem comes with the export. It creates a folder with a strange name inside adventures. Why is this a problem? When you have imported 30 adventures and you want to delete a particular one you have to go folder by folder to find the adventure you were looking for and delete it.

https://i.imgur.com/pzoYlfC.png

I would like to suggest that, as in importing, a folder called export should be created inside the adventurer folder and the exported adventurs should be unpacked there, and that instead of a folder with a strange name you could put the same name of the exported adventurs 

https://i.imgur.com/884yozV.png

https://i.imgur.com/3D8Pbjo.png

**Comment by cstadther** [comment]
Thanks for the suggestion!  The strange folder name is a unique identifier generated from within foundry.  I used that as the folder name for ease, but I see exactly where you're coming from.  Those folders are just locations to store images/music or any other files that are not the data.  I'll make the naming more manageable.

**Comment by altair984** [comment]
Particularly I think that the most orderly thing is that within the adventure folder, you have two folders, one importer and one exporter, and when you export an adventure, the folder is created within the exporter with the same name that you gave to the file we imported. example blackdragon.vttt to black dragon folder

If this were possible in this way, you would make me particularly very happy :D

**Comment by altair984** [comment]
Or excellent now doesn't create any directory or folder for you. Now directly reads all the information stored inside the *.fvttadv file

**Comment by cstadther** [comment]
I'm not sure it is 100% what you were looking for... I'm still working on better organization of the files on the server.

**Comment by altair984** [comment]
Before when you imported an adventure a folder with a strange name was created and inside there were the sounds, the images etc... now the program doesn't do that anymore, it reads it directly from the compressed file called *.fvttadv.

That's how it works, right?

**Comment by cstadther** [comment]
No, it still has to unpack the zip file and upload the files to Foundry to be able to use.  I'm modifying the folder name so that instead of the adventure id, it uses a sanitized version of the adventure name.  That will make it easier for cleanup.  The only issue would be in two adventures were named exactly the same.  Then all the uploaded files for both would reside in the same folder.
