### ISSUE TITLE
 Add file picker button to import path+

### ISSUE THREAD

**Issue by Goliathcraft** [cstadther/adventure-import-export#62]
This has already been suggested once and has been already implemented, but the fix didn't actually work for the problem (online host like forge). The problem is that this module requires something to be present in Data\adventures\import which is not directly accessible with forge. While the Add file picker button would fix it, the problem is that the query on which file to import only appears if a compatible file is already present at Data\adventures\import. 

I made sure to test it in my local foundry installation, and it also doesn't show the import query unless a compatible file is present (importing the files after I added them in the import folder worked, so did the file  picker, so I can be sure that there were no other errors). Unless there is some necessity for the query to only pop up when a file already located in Data\adventures\import, it would be useful to remove it to help out in this specific case.

**Comment by cstadther** [comment]
Now fixed in 0.4.8.  When its unable to verify the import path it will not block the dialog from showing.
