### ISSUE TITLE
Link ID doesn't update when link is already html, rather than markup

### ISSUE THREAD

**Issue by MickCrozier** [cstadther/adventure-import-export#72]
Hi Chris
Hoping this is this something fixable.

When a journal entry is <a class="entity-link" data-entity="JournalEntry" data-id="entityId">DisplayName</a>
Rather than @JournalEntry[EntityId]{DisplayName}
The ID's are not updated and the links break on import

**Comment by MickCrozier** [comment]
So normally it would be. But specifically in the KaKaRoTo's Roll20 Converter.
He uses HTML, rather than the link string. There's something about the link string that doesn't work for him. So it get's preconverted into the displayed HTML.

In the journal, the only way to edit it is to open the HTML viewer. And we see:
`<a class="entity-link" data-entity="JournalEntry" data-id="NmRkNzIyZDZkOWZj">Lighthouse</a>`
My understanding is that Foundry does this behind the scenes when it see's the markup link string to produce the nice buttons.
But in this case, it's not a link string, it's already HTML.

**Comment by cstadther** [comment]
That will be a little more difficult, but I am aware of this trick, in fact use it in the system I'm working on.  This is on my todo list.
