### ISSUE TITLE
Export Macros?

### ISSUE THREAD

**Issue by jbhuddleston** [cstadther/adventure-import-export#73]
Hi Chris,

I have reverted to 0.6.5 and everything you support that I need works perfectly, however, is it possible to collect the GMs macros? Or all players macros?
I can see all players being an issue but there will always be a GM. Thoughts?

Cheers,
James

**Comment by cstadther** [comment]
I'm pretty sure it is, it's on my todo list.

**Comment by MickCrozier** [comment]
Hi James - you can just copy the macros.db and players.db from one world to another.
Then you just need to hook the players back up to their characters.
It's not ideal but it's worked for me

**Comment by jbhuddleston** [comment]
Thanks for the tip. I hadn't thought of that.
James
