### ISSUE TITLE
Correct Clerical Error in Description

### ISSUE THREAD

**Issue by Razortide** [cstadther/adventure-import-export#83]
Hey, thank you for your great module.
It is just a small request, but since the module is the first one in my selection, I just wanted to point out that it states "Foundy" instead of "Foundry" in the description. I would appreciate it, if you could take the time to fix it 👍 
![grafik](https://user-images.githubusercontent.com/35796457/91621686-462ce380-e994-11ea-9f15-b9e7e94f9ac1.png)

**Comment by cstadther** [comment]
I take the typo bug any day :)

**Comment by cstadther** [comment]
Will be fixed in the next release 0.5.1
