### ISSUE TITLE
Cannot export actors that have "Randomize Wildcard Images" enabled

### ISSUE THREAD

**Issue by sneat** [cstadther/adventure-import-export#90]
The tool tries to download the raw URL (`/assets/commoners/*.png` in the example) which 404's and prevents the tool from progressing.

![image](https://user-images.githubusercontent.com/293277/92184755-5ada1180-ee95-11ea-9a09-94e144a7d21c.png)

Adventure Import/Export version: 0.5.1
FoundryVTT version: 0.7.1

**Comment by cstadther** [comment]
Thanks for finding this.  I'll take a look at see what I can do create a fix.

**Comment by cstadther** [comment]
This will be in the next release.  The only caveat, is this feature is not backward compatible.  Previously exported actors with the randomize token image did not include all the images.  Now when exporting, if there is a token with a randomize option set, it will include all files in the folder, and then re-add them when importing them.  Two tokens pointed to the same directory will not duplicate images, they will be shared between the two.

**Comment by sneat** [comment]
Wonderful!
